### PR TITLE
Update for PureScript 0.15

### PR DESCRIPTION
**Pull request by thomashoneyman**

### CODE REVIEW

**Comment by thomashoneyman** [comment]
I'm struggling to pin down where exactly the source of this problem is:

```
➜ spago test
[info] Build succeeded.
Main...

file:///home/trh/Desktop/purescript-node-workerbees/output/Effect.Aff/foreign.js:530
                throw util.fromLeft(step);
                ^
[worker eval]:1
import { worker } from "/home/trh/Desktop/purescript-node-workerbees/output/Test.Main/index.js;
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInThisContext (node:vm:305:10)
    at node:internal/process/execution:76:19
    at [worker eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:75:60)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:180:7)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[error] Tests failed: exit code: 1
```

I'd expect this to come from somewhere something like `node -e <contents>` was being called, but I'm struggling to track this all the way down.

**Comment by natefaubion** [comment]
It's probably coming from `jsEval`.

**Comment by thomashoneyman** [comment]
Without touching those lines (ie. leaving them as `require`, I get:

```
➜ node -e 'const Main = require("./output/Test.Main/index.js"); main();'
node:internal/modules/cjs/loader:1156
      throw err;
      ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/trh/Desktop/purescript-node-workerbees/output/Test.Main/index.js from /home/trh/Desktop/purescript-node-workerbees/[eval] not supported.
Instead change the require of index.js in /home/trh/Desktop/purescript-node-workerbees/[eval] to a dynamic import() which is available in all CommonJS modules.
    at [eval]:1:14
    at Script.runInThisContext (node:vm:129:12)
    at Object.runInThisContext (node:vm:305:38)
    at [eval]-wrapper:6:22 {
  code: 'ERR_REQUIRE_ESM'
}
```

The Node docs are all still using `require()`; I'm not sure how to convert it to ES modules, or if that's impossible, how to have the two module types play nicely together. I'll dig for now, but if you have advice I'm all ears.

**Comment by natefaubion** [comment]
Maybe you can pass in `--input-type=module` via `argv` or `execArgv` options?

**Comment by natefaubion** [comment]
You might have to use data URIs instead. https://github.com/nodejs/node/issues/30682#issuecomment-949731600

**Comment by thomashoneyman** [comment]
Ah, I forgot to mention I did try passing the flag via both `argv` and `execArgv`, but it didn't have any effect.

**Comment by thomashoneyman** [comment]
> You might have to use data URIs instead. [nodejs/node#30682 (comment)](https://github.com/nodejs/node/issues/30682#issuecomment-949731600)

This looks promising! I've got to run, but when I get back online I'll try it out.

**Comment by thomashoneyman** [comment]
Progress update: switching to a data url does indeed allow progress, but now I'm getting another failure:

```
Main...

file:///home/trh/Desktop/purescript-node-workerbees/output/Effect.Aff/foreign.js:530
                throw util.fromLeft(step);
                ^
TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at new NodeError (node:internal/errors:372:5)
    at fileURLToPath (node:internal/url:1422:11)
    at checkIfDisallowedImport (node:internal/modules/esm/resolve:1061:23)
    at defaultResolve (node:internal/modules/esm/resolve:1189:23)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_URL_SCHEME'
}
[error] Tests failed: exit code: 1
```

As usual, advice is appreciated, but I'll continue sleuthing!

**Comment by thomashoneyman** [comment]
I'm stumped -- even when the eval is just:

```js
import * as worker from "file:///home/trh/Desktop/purescript-node-workerbees/output/Test.Main/index.js";
```

...the error output is `TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file`. Evaluating something else instead, like:

```js
console.log("hello");
```

...works just fine, but obviously nothing has been imported.

**Comment by thomashoneyman** [comment]
@natefaubion I've removed the `make` function altogether as I couldn't get it working with imports. The updated tests show how it must be used (unsafely) until that can be resolved.

**Comment by natefaubion** [comment]
I think this looks good, but we should push it to a separate branch, not main.

**Comment by thomashoneyman** [comment]
[node-esm](https://github.com/natefaubion/purescript-node-workerbees/tree/node-esm)

**Pull request closed without merging**
